package com.getar.app.ui.theme

import androidx.compose.ui.graphics.Color

// Palet Light
val GetarPrimaryLight = Color(0xFFC2410C)
val GetarOnPrimaryLight = Color(0xFFFFFFFF)
val GetarPrimaryContainerLight = Color(0xFFFFDBCB)
val GetarOnPrimaryContainerLight = Color(0xFF3A0B00)
val GetarSecondaryLight = Color(0xFF475569)
val GetarOnSecondaryLight = Color(0xFFFFFFFF)
val GetarSecondaryContainerLight = Color(0xFFDDE3EA)
val GetarOnSecondaryContainerLight = Color(0xFF111C28)
val GetarTertiaryLight = Color(0xFF0F766E)
val GetarOnTertiaryLight = Color(0xFFFFFFFF)
val GetarTertiaryContainerLight = Color(0xFFBDF0E8)
val GetarOnTertiaryContainerLight = Color(0xFF00201C)
val GetarBackgroundLight = Color(0xFFFFF8F5)
val GetarOnBackgroundLight = Color(0xFF201A17)
val GetarSurfaceLight = Color(0xFFFFF8F5)
val GetarOnSurfaceLight = Color(0xFF201A17)
val GetarSurfaceVariantLight = Color(0xFFF4DED5)
val GetarOnSurfaceVariantLight = Color(0xFF52443D)
val GetarOutlineLight = Color(0xFF85736C)
val GetarOutlineVariantLight = Color(0xFFD8C2B9)
val GetarErrorLight = Color(0xFFBA1A1A)
val GetarOnErrorLight = Color(0xFFFFFFFF)
val GetarErrorContainerLight = Color(0xFFFFDAD6)
val GetarOnErrorContainerLight = Color(0xFF410002)

// Palet Dark
val GetarPrimaryDark = Color(0xFFFFB59A)
val GetarOnPrimaryDark = Color(0xFF5B1A00)
val GetarPrimaryContainerDark = Color(0xFF832700)
val GetarOnPrimaryContainerDark = Color(0xFFFFDBCB)
val GetarSecondaryDark = Color(0xFFB9C7D6)
val GetarOnSecondaryDark = Color(0xFF233140)
val GetarSecondaryContainerDark = Color(0xFF3A4857)
val GetarOnSecondaryContainerDark = Color(0xFFD5E3F3)
val GetarTertiaryDark = Color(0xFF82D5CB)
val GetarOnTertiaryDark = Color(0xFF003733)
val GetarTertiaryContainerDark = Color(0xFF00504A)
val GetarOnTertiaryContainerDark = Color(0xFFBDF0E8)
val GetarBackgroundDark = Color(0xFF181210)
val GetarOnBackgroundDark = Color(0xFFEDE0DB)
val GetarSurfaceDark = Color(0xFF181210)
val GetarOnSurfaceDark = Color(0xFFEDE0DB)
val GetarSurfaceVariantDark = Color(0xFF52443D)
val GetarOnSurfaceVariantDark = Color(0xFFD8C2B9)
val GetarOutlineDark = Color(0xFFA08D85)
val GetarOutlineVariantDark = Color(0xFF52443D)
val GetarErrorDark = Color(0xFFFFB4AB)
val GetarOnErrorDark = Color(0xFF690005)
val GetarErrorContainerDark = Color(0xFF93000A)
val GetarOnErrorContainerDark = Color(0xFFFFDAD6)

// Severity Colors (Light)
val SeverityMinorLight = Color(0xFF2E7D32)
val SeverityModerateLight = Color(0xFFEF6C00)
val SeverityStrongLight = Color(0xFFC62828)
val SeverityMajorLight = Color(0xFF6A1B9A)
val SeverityUnknownLight = Color(0xFF6B7280)
val OnSeverityLight = Color(0xFFFFFFFF)

// Severity Colors (Dark)
val SeverityMinorDark = Color(0xFF81C784)
val SeverityModerateDark = Color(0xFFFFB74D)
val SeverityStrongDark = Color(0xFFEF9A9A)
val SeverityMajorDark = Color(0xFFCE93D8)
val SeverityUnknownDark = Color(0xFF9CA3AF)

// Teks di atas badge severity saat Dark Mode
val OnSeverityMinorDark = Color(0xFF0B2D0E)
val OnSeverityModerateDark = Color(0xFF3A1D00)
val OnSeverityStrongDark = Color(0xFF410002)
val OnSeverityMajorDark = Color(0xFF2A0038)
val OnSeverityUnknownDark = Color(0xFF111827)